Spec style update
topdevexp/home pull request #1
Opened 2021-04-14 01:10 UTC by sunwei

根据md语法约定，调整了之前的样式。同时在readme中更新用法，将说明移到spec，因为这更像是对整个guidance的说明，而不是本repo的说明。

2021-04-14 01:11 UTC, sunwei commented
合并

2021-04-14 01:11 UTC, sunwei commented
关闭

2021-04-14 01:33 UTC, AliNL commented on weekly-catchup.md
> +没有购物环节，时间全花在景点上。通过定价的区别来看，大家普遍认为纯玩团体验会好一些。
这一行有两句话

2021-04-14 01:33 UTC, AliNL commented on weekly-catchup.md
> +有一个答案让我印象深刻。那就是 - 蝙蝠侠。大家可能很容易想到原因。
这一行有两句话

2021-04-14 01:33 UTC, AliNL commented on weekly-catchup.md
> +太精典，以至于深入人心。可这有什么好印象深刻的呢，多么朴实无华的理由！
这一行有两句话

2021-04-14 01:33 UTC, AliNL commented on weekly-catchup.md
> +出游时，旅行社会提供不同的选择，常见的有购物团和纯玩团。购物团就是到景点，5分钟拍照时间，剩余时间全部用来购物。
这一行有两句话

2021-04-14 01:34 UTC, AliNL commented on spec.md
> +衡量指标。DORA从"公司" - "团队" - "组织"的角度分析了研发效能，DPC则希望从开发者个人的角度来聊一聊研发效能。
这个换行位置好像不太对？

2021-04-14 01:35 UTC, AliNL requested changes
有些格式要改一下

2021-04-16 04:37 UTC, sunwei commented on weekly-catchup.md
> +没有购物环节，时间全花在景点上。通过定价的区别来看，大家普遍认为纯玩团体验会好一些。
已更新

2021-04-16 04:37 UTC, sunwei commented on weekly-catchup.md
> +有一个答案让我印象深刻。那就是 - 蝙蝠侠。大家可能很容易想到原因。
已更新换行

2021-04-16 04:37 UTC, sunwei commented on weekly-catchup.md
> +太精典，以至于深入人心。可这有什么好印象深刻的呢，多么朴实无华的理由！
已更新

2021-04-16 04:38 UTC, sunwei commented on weekly-catchup.md
> +出游时，旅行社会提供不同的选择，常见的有购物团和纯玩团。购物团就是到景点，5分钟拍照时间，剩余时间全部用来购物。
已更新

2021-04-16 04:38 UTC, sunwei commented on spec.md
> +衡量指标。DORA从"公司" - "团队" - "组织"的角度分析了研发效能，DPC则希望从开发者个人的角度来聊一聊研发效能。
已更新

2021-04-16 04:43 UTC, AliNL approved these changes

2021-04-16 04:43 UTC, merged